name: Test, Build, and Deploy

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.6.0'

      - name: Install pnpm
        run: |
          npm install -g pnpm
          pnpm setup
          echo "PNPM_HOME=$HOME/.local/share/pnpm" >> $GITHUB_ENV
          echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH
        shell: bash
        env:
          SHELL: /bin/bash

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run lighthouse
        run: |
          pnpm install -g @lhci/cli@0.13.0
          pnpm run lighthouse
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: Upload lighthouse Reports
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-reports
          path: lighthouse-reports/
